name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest
    
    # on-hover of the checkmark, show "Ruby 3 / Redis 6" instead of "(3 / 6)"
    name: "Ruby ${{ matrix.ruby }} / Redis ${{ matrix.redis }}"

    strategy:
      fail-fast: false
      matrix:
        ruby: ["2.7", "3.0", "3.1", "3.2"]
        redis: [6, 7]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby ${{ matrix.ruby }}
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true # 'bundle install' and cache gems
        ruby-version: ${{ matrix.ruby }}
    - name: Set up Redis ${{ matrix.redis }}
      uses: supercharge/redis-github-action@1.6.0
      with:
        redis-version: ${{ matrix.redis }}        
    - name: Run tests
      run: bundle exec rake
